// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "avatar", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "email", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "sex", Type: field.TypeString, Size: 6, Default: ""},
		{Name: "age", Type: field.TypeUint64, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// UserStatColumns holds the columns for the "user_stat" table.
	UserStatColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "followers_count", Type: field.TypeUint64, Default: 0},
		{Name: "following_count", Type: field.TypeUint64, Default: 0},
		{Name: "like_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_like_count", Type: field.TypeUint64, Default: 0},
		{Name: "view_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_view_count", Type: field.TypeUint64, Default: 0},
		{Name: "favor_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_favor_count", Type: field.TypeUint64, Default: 0},
		{Name: "user_id", Type: field.TypeUint64, Unique: true},
	}
	// UserStatTable holds the schema information for the "user_stat" table.
	UserStatTable = &schema.Table{
		Name:       "user_stat",
		Columns:    UserStatColumns,
		PrimaryKey: []*schema.Column{UserStatColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_stat_user_stat",
				Columns:    []*schema.Column{UserStatColumns[12]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
		UserStatTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserStatTable.ForeignKeys[0].RefTable = UserTable
	UserStatTable.Annotation = &entsql.Annotation{
		Table: "user_stat",
	}
}
