// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArticleColumns holds the columns for the "article" table.
	ArticleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString},
		{Name: "cover_image", Type: field.TypeString, Default: ""},
		{Name: "is_top", Type: field.TypeBool, Default: false},
		{Name: "is_published", Type: field.TypeBool, Default: true},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "like_count", Type: field.TypeInt, Default: 0},
		{Name: "favor_count", Type: field.TypeInt, Default: 0},
		{Name: "comment_count", Type: field.TypeInt, Default: 0},
		{Name: "category_id", Type: field.TypeUint64, Unique: true},
		{Name: "author_id", Type: field.TypeUint64, Unique: true},
	}
	// ArticleTable holds the schema information for the "article" table.
	ArticleTable = &schema.Table{
		Name:       "article",
		Columns:    ArticleColumns,
		PrimaryKey: []*schema.Column{ArticleColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "article_category_articles",
				Columns:    []*schema.Column{ArticleColumns[15]},
				RefColumns: []*schema.Column{CategoryColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "article_user_articles",
				Columns:    []*schema.Column{ArticleColumns[16]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CategoryColumns holds the columns for the "category" table.
	CategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeUint64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 64},
	}
	// CategoryTable holds the schema information for the "category" table.
	CategoryTable = &schema.Table{
		Name:       "category",
		Columns:    CategoryColumns,
		PrimaryKey: []*schema.Column{CategoryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "category_parent_id_name",
				Unique:  true,
				Columns: []*schema.Column{CategoryColumns[3], CategoryColumns[4]},
			},
		},
	}
	// CommentColumns holds the columns for the "comment" table.
	CommentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "parent_id", Type: field.TypeUint64, Default: 0},
		{Name: "root_id", Type: field.TypeUint64, Default: 0},
		{Name: "reply_to_id", Type: field.TypeUint64, Default: 0},
		{Name: "content", Type: field.TypeString},
		{Name: "like_count", Type: field.TypeUint32, Default: 0},
		{Name: "child_count", Type: field.TypeUint32, Default: 0},
		{Name: "article_id", Type: field.TypeUint64},
		{Name: "user_id", Type: field.TypeUint64},
	}
	// CommentTable holds the schema information for the "comment" table.
	CommentTable = &schema.Table{
		Name:       "comment",
		Columns:    CommentColumns,
		PrimaryKey: []*schema.Column{CommentColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comment_article_comments",
				Columns:    []*schema.Column{CommentColumns[9]},
				RefColumns: []*schema.Column{ArticleColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "comment_user_comments",
				Columns:    []*schema.Column{CommentColumns[10]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InteractionCountColumns holds the columns for the "interaction_count" table.
	InteractionCountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "object_id", Type: field.TypeUint64},
		{Name: "object_type", Type: field.TypeEnum, Enums: []string{"article", "comment", "life"}},
		{Name: "interaction_type", Type: field.TypeEnum, Enums: []string{"like", "comment", "view", "favor"}},
		{Name: "count", Type: field.TypeInt, Default: 0},
	}
	// InteractionCountTable holds the schema information for the "interaction_count" table.
	InteractionCountTable = &schema.Table{
		Name:       "interaction_count",
		Columns:    InteractionCountColumns,
		PrimaryKey: []*schema.Column{InteractionCountColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uk_object",
				Unique:  true,
				Columns: []*schema.Column{InteractionCountColumns[3], InteractionCountColumns[4], InteractionCountColumns[5]},
			},
		},
	}
	// InteractionLikeColumns holds the columns for the "interaction_like" table.
	InteractionLikeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "object_type", Type: field.TypeEnum, Enums: []string{"article", "comment", "life"}},
		{Name: "object_id", Type: field.TypeUint64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"unknown", "thumb_up", "nothing"}, Default: "nothing"},
		{Name: "version", Type: field.TypeInt64, Default: 0},
	}
	// InteractionLikeTable holds the schema information for the "interaction_like" table.
	InteractionLikeTable = &schema.Table{
		Name:       "interaction_like",
		Columns:    InteractionLikeColumns,
		PrimaryKey: []*schema.Column{InteractionLikeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uk_like_user_object",
				Unique:  true,
				Columns: []*schema.Column{InteractionLikeColumns[3], InteractionLikeColumns[4], InteractionLikeColumns[5]},
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString, Size: 20},
		{Name: "phone", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "avatar", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "email", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "sex", Type: field.TypeEnum, Enums: []string{"male", "female", "secret", "unknown"}, Default: "unknown"},
		{Name: "birthday", Type: field.TypeTime, Nullable: true},
		{Name: "signature", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"approved", "blocked"}, Default: "approved"},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// UserStatColumns holds the columns for the "user_stat" table.
	UserStatColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "article_count", Type: field.TypeUint64, Nullable: true},
		{Name: "followers_count", Type: field.TypeUint64, Default: 0},
		{Name: "following_count", Type: field.TypeUint64, Default: 0},
		{Name: "like_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_like_count", Type: field.TypeUint64, Default: 0},
		{Name: "favor_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_favor_count", Type: field.TypeUint64, Default: 0},
		{Name: "user_id", Type: field.TypeUint64, Unique: true},
	}
	// UserStatTable holds the schema information for the "user_stat" table.
	UserStatTable = &schema.Table{
		Name:       "user_stat",
		Columns:    UserStatColumns,
		PrimaryKey: []*schema.Column{UserStatColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_stat_user_stat",
				Columns:    []*schema.Column{UserStatColumns[11]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArticleTable,
		CategoryTable,
		CommentTable,
		InteractionCountTable,
		InteractionLikeTable,
		UserTable,
		UserStatTable,
	}
)

func init() {
	ArticleTable.ForeignKeys[0].RefTable = CategoryTable
	ArticleTable.ForeignKeys[1].RefTable = UserTable
	ArticleTable.Annotation = &entsql.Annotation{
		Table: "article",
	}
	CategoryTable.Annotation = &entsql.Annotation{
		Table: "category",
	}
	CommentTable.ForeignKeys[0].RefTable = ArticleTable
	CommentTable.ForeignKeys[1].RefTable = UserTable
	CommentTable.Annotation = &entsql.Annotation{
		Table: "comment",
	}
	InteractionCountTable.Annotation = &entsql.Annotation{
		Table: "interaction_count",
	}
	InteractionLikeTable.Annotation = &entsql.Annotation{
		Table: "interaction_like",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserStatTable.ForeignKeys[0].RefTable = UserTable
	UserStatTable.Annotation = &entsql.Annotation{
		Table: "user_stat",
	}
}
