// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "avatar", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "email", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "sex", Type: field.TypeString, Size: 6, Default: ""},
		{Name: "age", Type: field.TypeUint64, Default: 0},
		{Name: "like_count", Type: field.TypeUint64, Default: 0},
		{Name: "receive_like_count", Type: field.TypeUint64, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "auth_version", Type: field.TypeUint64, Default: 1},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
