// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/article"
	"core-server/internal/infras/repov2/ent/comment"
	"core-server/internal/infras/repov2/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentCreate is the builder for creating a Comment entity.
type CommentCreate struct {
	config
	mutation *CommentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommentCreate) SetCreatedAt(v time.Time) *CommentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CommentCreate) SetNillableCreatedAt(v *time.Time) *CommentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CommentCreate) SetDeletedAt(v time.Time) *CommentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CommentCreate) SetNillableDeletedAt(v *time.Time) *CommentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetArticleID sets the "article_id" field.
func (_c *CommentCreate) SetArticleID(v uint64) *CommentCreate {
	_c.mutation.SetArticleID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CommentCreate) SetUserID(v uint64) *CommentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *CommentCreate) SetParentID(v uint64) *CommentCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *CommentCreate) SetNillableParentID(v *uint64) *CommentCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetRootID sets the "root_id" field.
func (_c *CommentCreate) SetRootID(v uint64) *CommentCreate {
	_c.mutation.SetRootID(v)
	return _c
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_c *CommentCreate) SetNillableRootID(v *uint64) *CommentCreate {
	if v != nil {
		_c.SetRootID(*v)
	}
	return _c
}

// SetReplyToID sets the "reply_to_id" field.
func (_c *CommentCreate) SetReplyToID(v uint64) *CommentCreate {
	_c.mutation.SetReplyToID(v)
	return _c
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_c *CommentCreate) SetNillableReplyToID(v *uint64) *CommentCreate {
	if v != nil {
		_c.SetReplyToID(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *CommentCreate) SetContent(v string) *CommentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *CommentCreate) SetLikeCount(v uint32) *CommentCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *CommentCreate) SetNillableLikeCount(v *uint32) *CommentCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetChildCount sets the "child_count" field.
func (_c *CommentCreate) SetChildCount(v uint32) *CommentCreate {
	_c.mutation.SetChildCount(v)
	return _c
}

// SetNillableChildCount sets the "child_count" field if the given value is not nil.
func (_c *CommentCreate) SetNillableChildCount(v *uint32) *CommentCreate {
	if v != nil {
		_c.SetChildCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CommentCreate) SetID(v uint64) *CommentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetArticle sets the "article" edge to the Article entity.
func (_c *CommentCreate) SetArticle(v *Article) *CommentCreate {
	return _c.SetArticleID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *CommentCreate) SetUser(v *User) *CommentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_c *CommentCreate) Mutation() *CommentMutation {
	return _c.mutation
}

// Save creates the Comment in the database.
func (_c *CommentCreate) Save(ctx context.Context) (*Comment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommentCreate) SaveX(ctx context.Context) *Comment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := comment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := comment.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.RootID(); !ok {
		v := comment.DefaultRootID
		_c.mutation.SetRootID(v)
	}
	if _, ok := _c.mutation.ReplyToID(); !ok {
		v := comment.DefaultReplyToID
		_c.mutation.SetReplyToID(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := comment.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.ChildCount(); !ok {
		v := comment.DefaultChildCount
		_c.mutation.SetChildCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Comment.created_at"`)}
	}
	if _, ok := _c.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "Comment.article_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Comment.user_id"`)}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Comment.parent_id"`)}
	}
	if _, ok := _c.mutation.RootID(); !ok {
		return &ValidationError{Name: "root_id", err: errors.New(`ent: missing required field "Comment.root_id"`)}
	}
	if _, ok := _c.mutation.ReplyToID(); !ok {
		return &ValidationError{Name: "reply_to_id", err: errors.New(`ent: missing required field "Comment.reply_to_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Comment.content"`)}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "Comment.like_count"`)}
	}
	if _, ok := _c.mutation.ChildCount(); !ok {
		return &ValidationError{Name: "child_count", err: errors.New(`ent: missing required field "Comment.child_count"`)}
	}
	if len(_c.mutation.ArticleIDs()) == 0 {
		return &ValidationError{Name: "article", err: errors.New(`ent: missing required edge "Comment.article"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Comment.user"`)}
	}
	return nil
}

func (_c *CommentCreate) sqlSave(ctx context.Context) (*Comment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommentCreate) createSpec() (*Comment, *sqlgraph.CreateSpec) {
	var (
		_node = &Comment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(comment.Table, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(comment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(comment.FieldParentID, field.TypeUint64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.RootID(); ok {
		_spec.SetField(comment.FieldRootID, field.TypeUint64, value)
		_node.RootID = value
	}
	if value, ok := _c.mutation.ReplyToID(); ok {
		_spec.SetField(comment.FieldReplyToID, field.TypeUint64, value)
		_node.ReplyToID = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(comment.FieldLikeCount, field.TypeUint32, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.ChildCount(); ok {
		_spec.SetField(comment.FieldChildCount, field.TypeUint32, value)
		_node.ChildCount = value
	}
	if nodes := _c.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ArticleTable,
			Columns: []string{comment.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ArticleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.UserTable,
			Columns: []string{comment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommentCreateBulk is the builder for creating many Comment entities in bulk.
type CommentCreateBulk struct {
	config
	err      error
	builders []*CommentCreate
}

// Save creates the Comment entities in the database.
func (_c *CommentCreateBulk) Save(ctx context.Context) ([]*Comment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Comment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommentCreateBulk) SaveX(ctx context.Context) []*Comment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
