// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/interactionlike"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InteractionLikeCreate is the builder for creating a InteractionLike entity.
type InteractionLikeCreate struct {
	config
	mutation *InteractionLikeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *InteractionLikeCreate) SetCreatedAt(v time.Time) *InteractionLikeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InteractionLikeCreate) SetNillableCreatedAt(v *time.Time) *InteractionLikeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InteractionLikeCreate) SetUpdatedAt(v time.Time) *InteractionLikeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InteractionLikeCreate) SetNillableUpdatedAt(v *time.Time) *InteractionLikeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InteractionLikeCreate) SetUserID(v uint64) *InteractionLikeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetObjectType sets the "object_type" field.
func (_c *InteractionLikeCreate) SetObjectType(v interactionlike.ObjectType) *InteractionLikeCreate {
	_c.mutation.SetObjectType(v)
	return _c
}

// SetObjectID sets the "object_id" field.
func (_c *InteractionLikeCreate) SetObjectID(v uint64) *InteractionLikeCreate {
	_c.mutation.SetObjectID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InteractionLikeCreate) SetStatus(v interactionlike.Status) *InteractionLikeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InteractionLikeCreate) SetNillableStatus(v *interactionlike.Status) *InteractionLikeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *InteractionLikeCreate) SetVersion(v int64) *InteractionLikeCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *InteractionLikeCreate) SetNillableVersion(v *int64) *InteractionLikeCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InteractionLikeCreate) SetID(v uint64) *InteractionLikeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InteractionLikeMutation object of the builder.
func (_c *InteractionLikeCreate) Mutation() *InteractionLikeMutation {
	return _c.mutation
}

// Save creates the InteractionLike in the database.
func (_c *InteractionLikeCreate) Save(ctx context.Context) (*InteractionLike, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InteractionLikeCreate) SaveX(ctx context.Context) *InteractionLike {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InteractionLikeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InteractionLikeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InteractionLikeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := interactionlike.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := interactionlike.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := interactionlike.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := interactionlike.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InteractionLikeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InteractionLike.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InteractionLike.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InteractionLike.user_id"`)}
	}
	if _, ok := _c.mutation.ObjectType(); !ok {
		return &ValidationError{Name: "object_type", err: errors.New(`ent: missing required field "InteractionLike.object_type"`)}
	}
	if v, ok := _c.mutation.ObjectType(); ok {
		if err := interactionlike.ObjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "object_type", err: fmt.Errorf(`ent: validator failed for field "InteractionLike.object_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "object_id", err: errors.New(`ent: missing required field "InteractionLike.object_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InteractionLike.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := interactionlike.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InteractionLike.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "InteractionLike.version"`)}
	}
	return nil
}

func (_c *InteractionLikeCreate) sqlSave(ctx context.Context) (*InteractionLike, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InteractionLikeCreate) createSpec() (*InteractionLike, *sqlgraph.CreateSpec) {
	var (
		_node = &InteractionLike{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(interactionlike.Table, sqlgraph.NewFieldSpec(interactionlike.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(interactionlike.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(interactionlike.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(interactionlike.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ObjectType(); ok {
		_spec.SetField(interactionlike.FieldObjectType, field.TypeEnum, value)
		_node.ObjectType = value
	}
	if value, ok := _c.mutation.ObjectID(); ok {
		_spec.SetField(interactionlike.FieldObjectID, field.TypeUint64, value)
		_node.ObjectID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(interactionlike.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(interactionlike.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	return _node, _spec
}

// InteractionLikeCreateBulk is the builder for creating many InteractionLike entities in bulk.
type InteractionLikeCreateBulk struct {
	config
	err      error
	builders []*InteractionLikeCreate
}

// Save creates the InteractionLike entities in the database.
func (_c *InteractionLikeCreateBulk) Save(ctx context.Context) ([]*InteractionLike, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InteractionLike, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InteractionLikeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InteractionLikeCreateBulk) SaveX(ctx context.Context) []*InteractionLike {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InteractionLikeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InteractionLikeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
