// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/interactioncount"
	"core-server/internal/infras/repov2/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InteractionCountUpdate is the builder for updating InteractionCount entities.
type InteractionCountUpdate struct {
	config
	hooks    []Hook
	mutation *InteractionCountMutation
}

// Where appends a list predicates to the InteractionCountUpdate builder.
func (_u *InteractionCountUpdate) Where(ps ...predicate.InteractionCount) *InteractionCountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InteractionCountUpdate) SetUpdatedAt(v time.Time) *InteractionCountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *InteractionCountUpdate) SetObjectID(v uint64) *InteractionCountUpdate {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *InteractionCountUpdate) SetNillableObjectID(v *uint64) *InteractionCountUpdate {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *InteractionCountUpdate) AddObjectID(v int64) *InteractionCountUpdate {
	_u.mutation.AddObjectID(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *InteractionCountUpdate) SetCount(v int) *InteractionCountUpdate {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *InteractionCountUpdate) SetNillableCount(v *int) *InteractionCountUpdate {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *InteractionCountUpdate) AddCount(v int) *InteractionCountUpdate {
	_u.mutation.AddCount(v)
	return _u
}

// Mutation returns the InteractionCountMutation object of the builder.
func (_u *InteractionCountUpdate) Mutation() *InteractionCountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InteractionCountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InteractionCountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InteractionCountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InteractionCountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InteractionCountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := interactioncount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *InteractionCountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(interactioncount.Table, interactioncount.Columns, sqlgraph.NewFieldSpec(interactioncount.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interactioncount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(interactioncount.FieldObjectID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(interactioncount.FieldObjectID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(interactioncount.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(interactioncount.FieldCount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interactioncount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InteractionCountUpdateOne is the builder for updating a single InteractionCount entity.
type InteractionCountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InteractionCountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InteractionCountUpdateOne) SetUpdatedAt(v time.Time) *InteractionCountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *InteractionCountUpdateOne) SetObjectID(v uint64) *InteractionCountUpdateOne {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *InteractionCountUpdateOne) SetNillableObjectID(v *uint64) *InteractionCountUpdateOne {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *InteractionCountUpdateOne) AddObjectID(v int64) *InteractionCountUpdateOne {
	_u.mutation.AddObjectID(v)
	return _u
}

// SetCount sets the "count" field.
func (_u *InteractionCountUpdateOne) SetCount(v int) *InteractionCountUpdateOne {
	_u.mutation.ResetCount()
	_u.mutation.SetCount(v)
	return _u
}

// SetNillableCount sets the "count" field if the given value is not nil.
func (_u *InteractionCountUpdateOne) SetNillableCount(v *int) *InteractionCountUpdateOne {
	if v != nil {
		_u.SetCount(*v)
	}
	return _u
}

// AddCount adds value to the "count" field.
func (_u *InteractionCountUpdateOne) AddCount(v int) *InteractionCountUpdateOne {
	_u.mutation.AddCount(v)
	return _u
}

// Mutation returns the InteractionCountMutation object of the builder.
func (_u *InteractionCountUpdateOne) Mutation() *InteractionCountMutation {
	return _u.mutation
}

// Where appends a list predicates to the InteractionCountUpdate builder.
func (_u *InteractionCountUpdateOne) Where(ps ...predicate.InteractionCount) *InteractionCountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InteractionCountUpdateOne) Select(field string, fields ...string) *InteractionCountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InteractionCount entity.
func (_u *InteractionCountUpdateOne) Save(ctx context.Context) (*InteractionCount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InteractionCountUpdateOne) SaveX(ctx context.Context) *InteractionCount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InteractionCountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InteractionCountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InteractionCountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := interactioncount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *InteractionCountUpdateOne) sqlSave(ctx context.Context) (_node *InteractionCount, err error) {
	_spec := sqlgraph.NewUpdateSpec(interactioncount.Table, interactioncount.Columns, sqlgraph.NewFieldSpec(interactioncount.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InteractionCount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interactioncount.FieldID)
		for _, f := range fields {
			if !interactioncount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != interactioncount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interactioncount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(interactioncount.FieldObjectID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(interactioncount.FieldObjectID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Count(); ok {
		_spec.SetField(interactioncount.FieldCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.AddField(interactioncount.FieldCount, field.TypeInt, value)
	}
	_node = &InteractionCount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interactioncount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
