// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/interactioncount"
	"core-server/internal/infras/repov2/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InteractionCountDelete is the builder for deleting a InteractionCount entity.
type InteractionCountDelete struct {
	config
	hooks    []Hook
	mutation *InteractionCountMutation
}

// Where appends a list predicates to the InteractionCountDelete builder.
func (_d *InteractionCountDelete) Where(ps ...predicate.InteractionCount) *InteractionCountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InteractionCountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InteractionCountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InteractionCountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interactioncount.Table, sqlgraph.NewFieldSpec(interactioncount.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InteractionCountDeleteOne is the builder for deleting a single InteractionCount entity.
type InteractionCountDeleteOne struct {
	_d *InteractionCountDelete
}

// Where appends a list predicates to the InteractionCountDelete builder.
func (_d *InteractionCountDeleteOne) Where(ps ...predicate.InteractionCount) *InteractionCountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InteractionCountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interactioncount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InteractionCountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
