// Code generated by ent, DO NOT EDIT.

package ent

import (
	"core-server/internal/infras/repov2/ent/schema"
	"core-server/internal/infras/repov2/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[6].Descriptor()
	// user.DefaultPhone holds the default value on creation for the phone field.
	user.DefaultPhone = userDescPhone.Default.(string)
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[7].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[8].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[9].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescSex is the schema descriptor for sex field.
	userDescSex := userFields[10].Descriptor()
	// user.DefaultSex holds the default value on creation for the sex field.
	user.DefaultSex = userDescSex.Default.(string)
	// user.SexValidator is a validator for the "sex" field. It is called by the builders before save.
	user.SexValidator = userDescSex.Validators[0].(func(string) error)
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[11].Descriptor()
	// user.DefaultAge holds the default value on creation for the age field.
	user.DefaultAge = userDescAge.Default.(uint64)
	// userDescLikeCount is the schema descriptor for like_count field.
	userDescLikeCount := userFields[12].Descriptor()
	// user.DefaultLikeCount holds the default value on creation for the like_count field.
	user.DefaultLikeCount = userDescLikeCount.Default.(uint64)
	// userDescReceiveLikeCount is the schema descriptor for receive_like_count field.
	userDescReceiveLikeCount := userFields[13].Descriptor()
	// user.DefaultReceiveLikeCount holds the default value on creation for the receive_like_count field.
	user.DefaultReceiveLikeCount = userDescReceiveLikeCount.Default.(uint64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[14].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescAuthVersion is the schema descriptor for auth_version field.
	userDescAuthVersion := userFields[15].Descriptor()
	// user.DefaultAuthVersion holds the default value on creation for the auth_version field.
	user.DefaultAuthVersion = userDescAuthVersion.Default.(uint64)
}
