// Code generated by ent, DO NOT EDIT.

package ent

import (
	"core-server/internal/infras/repov2/ent/category"
	"core-server/internal/infras/repov2/ent/schema"
	"core-server/internal/infras/repov2/ent/user"
	"core-server/internal/infras/repov2/ent/userstat"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[1].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[2].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescParentID is the schema descriptor for parent_id field.
	categoryDescParentID := categoryFields[4].Descriptor()
	// category.DefaultParentID holds the default value on creation for the parent_id field.
	category.DefaultParentID = categoryDescParentID.Default.(uint64)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[5].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[6].Descriptor()
	// user.DefaultPhone holds the default value on creation for the phone field.
	user.DefaultPhone = userDescPhone.Default.(string)
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[7].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[8].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[9].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescSex is the schema descriptor for sex field.
	userDescSex := userFields[10].Descriptor()
	// user.DefaultSex holds the default value on creation for the sex field.
	user.DefaultSex = userDescSex.Default.(string)
	// user.SexValidator is a validator for the "sex" field. It is called by the builders before save.
	user.SexValidator = userDescSex.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[12].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	userstatFields := schema.UserStat{}.Fields()
	_ = userstatFields
	// userstatDescCreatedAt is the schema descriptor for created_at field.
	userstatDescCreatedAt := userstatFields[0].Descriptor()
	// userstat.DefaultCreatedAt holds the default value on creation for the created_at field.
	userstat.DefaultCreatedAt = userstatDescCreatedAt.Default.(func() time.Time)
	// userstatDescUpdatedAt is the schema descriptor for updated_at field.
	userstatDescUpdatedAt := userstatFields[1].Descriptor()
	// userstat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userstat.DefaultUpdatedAt = userstatDescUpdatedAt.Default.(func() time.Time)
	// userstat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userstat.UpdateDefaultUpdatedAt = userstatDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userstatDescFollowersCount is the schema descriptor for followers_count field.
	userstatDescFollowersCount := userstatFields[5].Descriptor()
	// userstat.DefaultFollowersCount holds the default value on creation for the followers_count field.
	userstat.DefaultFollowersCount = userstatDescFollowersCount.Default.(uint64)
	// userstatDescFollowingCount is the schema descriptor for following_count field.
	userstatDescFollowingCount := userstatFields[6].Descriptor()
	// userstat.DefaultFollowingCount holds the default value on creation for the following_count field.
	userstat.DefaultFollowingCount = userstatDescFollowingCount.Default.(uint64)
	// userstatDescLikeCount is the schema descriptor for like_count field.
	userstatDescLikeCount := userstatFields[7].Descriptor()
	// userstat.DefaultLikeCount holds the default value on creation for the like_count field.
	userstat.DefaultLikeCount = userstatDescLikeCount.Default.(uint64)
	// userstatDescReceiveLikeCount is the schema descriptor for receive_like_count field.
	userstatDescReceiveLikeCount := userstatFields[8].Descriptor()
	// userstat.DefaultReceiveLikeCount holds the default value on creation for the receive_like_count field.
	userstat.DefaultReceiveLikeCount = userstatDescReceiveLikeCount.Default.(uint64)
	// userstatDescFavorCount is the schema descriptor for favor_count field.
	userstatDescFavorCount := userstatFields[9].Descriptor()
	// userstat.DefaultFavorCount holds the default value on creation for the favor_count field.
	userstat.DefaultFavorCount = userstatDescFavorCount.Default.(uint64)
	// userstatDescReceiveFavorCount is the schema descriptor for receive_favor_count field.
	userstatDescReceiveFavorCount := userstatFields[10].Descriptor()
	// userstat.DefaultReceiveFavorCount holds the default value on creation for the receive_favor_count field.
	userstat.DefaultReceiveFavorCount = userstatDescReceiveFavorCount.Default.(uint64)
}
