// Code generated by ent, DO NOT EDIT.

package ent

import (
	"core-server/internal/infras/repov2/ent/user"
	"core-server/internal/infras/repov2/ent/userstat"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserStat is the model entity for the UserStat schema.
type UserStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// FollowersCount holds the value of the "followers_count" field.
	FollowersCount uint64 `json:"followers_count,omitempty"`
	// FollowingCount holds the value of the "following_count" field.
	FollowingCount uint64 `json:"following_count,omitempty"`
	// LikeCount holds the value of the "like_count" field.
	LikeCount uint64 `json:"like_count,omitempty"`
	// ReceiveLikeCount holds the value of the "receive_like_count" field.
	ReceiveLikeCount uint64 `json:"receive_like_count,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount uint64 `json:"view_count,omitempty"`
	// ReceiveViewCount holds the value of the "receive_view_count" field.
	ReceiveViewCount uint64 `json:"receive_view_count,omitempty"`
	// FavorCount holds the value of the "favor_count" field.
	FavorCount uint64 `json:"favor_count,omitempty"`
	// ReceiveFavorCount holds the value of the "receive_favor_count" field.
	ReceiveFavorCount uint64 `json:"receive_favor_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserStatQuery when eager-loading is set.
	Edges        UserStatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserStatEdges holds the relations/edges for other nodes in the graph.
type UserStatEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserStatEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userstat.FieldID, userstat.FieldUserID, userstat.FieldFollowersCount, userstat.FieldFollowingCount, userstat.FieldLikeCount, userstat.FieldReceiveLikeCount, userstat.FieldViewCount, userstat.FieldReceiveViewCount, userstat.FieldFavorCount, userstat.FieldReceiveFavorCount:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserStat fields.
func (_m *UserStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userstat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userstat.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case userstat.FieldFollowersCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field followers_count", values[i])
			} else if value.Valid {
				_m.FollowersCount = uint64(value.Int64)
			}
		case userstat.FieldFollowingCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field following_count", values[i])
			} else if value.Valid {
				_m.FollowingCount = uint64(value.Int64)
			}
		case userstat.FieldLikeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field like_count", values[i])
			} else if value.Valid {
				_m.LikeCount = uint64(value.Int64)
			}
		case userstat.FieldReceiveLikeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receive_like_count", values[i])
			} else if value.Valid {
				_m.ReceiveLikeCount = uint64(value.Int64)
			}
		case userstat.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = uint64(value.Int64)
			}
		case userstat.FieldReceiveViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receive_view_count", values[i])
			} else if value.Valid {
				_m.ReceiveViewCount = uint64(value.Int64)
			}
		case userstat.FieldFavorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field favor_count", values[i])
			} else if value.Valid {
				_m.FavorCount = uint64(value.Int64)
			}
		case userstat.FieldReceiveFavorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receive_favor_count", values[i])
			} else if value.Valid {
				_m.ReceiveFavorCount = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserStat.
// This includes values selected through modifiers, order, etc.
func (_m *UserStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserStat entity.
func (_m *UserStat) QueryUser() *UserQuery {
	return NewUserStatClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserStat.
// Note that you need to call UserStat.Unwrap() before calling this method if this UserStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserStat) Update() *UserStatUpdateOne {
	return NewUserStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserStat) Unwrap() *UserStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserStat) String() string {
	var builder strings.Builder
	builder.WriteString("UserStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("followers_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FollowersCount))
	builder.WriteString(", ")
	builder.WriteString("following_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FollowingCount))
	builder.WriteString(", ")
	builder.WriteString("like_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LikeCount))
	builder.WriteString(", ")
	builder.WriteString("receive_like_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveLikeCount))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	builder.WriteString("receive_view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveViewCount))
	builder.WriteString(", ")
	builder.WriteString("favor_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FavorCount))
	builder.WriteString(", ")
	builder.WriteString("receive_favor_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveFavorCount))
	builder.WriteByte(')')
	return builder.String()
}

// UserStats is a parsable slice of UserStat.
type UserStats []*UserStat
