// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/predicate"
	"core-server/internal/infras/repov2/ent/user"
	"core-server/internal/infras/repov2/ent/userstat"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserStatUpdate is the builder for updating UserStat entities.
type UserStatUpdate struct {
	config
	hooks    []Hook
	mutation *UserStatMutation
}

// Where appends a list predicates to the UserStatUpdate builder.
func (_u *UserStatUpdate) Where(ps ...predicate.UserStat) *UserStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserStatUpdate) SetUserID(v uint64) *UserStatUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableUserID(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFollowersCount sets the "followers_count" field.
func (_u *UserStatUpdate) SetFollowersCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetFollowersCount()
	_u.mutation.SetFollowersCount(v)
	return _u
}

// SetNillableFollowersCount sets the "followers_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableFollowersCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetFollowersCount(*v)
	}
	return _u
}

// AddFollowersCount adds value to the "followers_count" field.
func (_u *UserStatUpdate) AddFollowersCount(v int64) *UserStatUpdate {
	_u.mutation.AddFollowersCount(v)
	return _u
}

// SetFollowingCount sets the "following_count" field.
func (_u *UserStatUpdate) SetFollowingCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetFollowingCount()
	_u.mutation.SetFollowingCount(v)
	return _u
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableFollowingCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetFollowingCount(*v)
	}
	return _u
}

// AddFollowingCount adds value to the "following_count" field.
func (_u *UserStatUpdate) AddFollowingCount(v int64) *UserStatUpdate {
	_u.mutation.AddFollowingCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *UserStatUpdate) SetLikeCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableLikeCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *UserStatUpdate) AddLikeCount(v int64) *UserStatUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetReceiveLikeCount sets the "receive_like_count" field.
func (_u *UserStatUpdate) SetReceiveLikeCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetReceiveLikeCount()
	_u.mutation.SetReceiveLikeCount(v)
	return _u
}

// SetNillableReceiveLikeCount sets the "receive_like_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableReceiveLikeCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetReceiveLikeCount(*v)
	}
	return _u
}

// AddReceiveLikeCount adds value to the "receive_like_count" field.
func (_u *UserStatUpdate) AddReceiveLikeCount(v int64) *UserStatUpdate {
	_u.mutation.AddReceiveLikeCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *UserStatUpdate) SetViewCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableViewCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *UserStatUpdate) AddViewCount(v int64) *UserStatUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetReceiveViewCount sets the "receive_view_count" field.
func (_u *UserStatUpdate) SetReceiveViewCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetReceiveViewCount()
	_u.mutation.SetReceiveViewCount(v)
	return _u
}

// SetNillableReceiveViewCount sets the "receive_view_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableReceiveViewCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetReceiveViewCount(*v)
	}
	return _u
}

// AddReceiveViewCount adds value to the "receive_view_count" field.
func (_u *UserStatUpdate) AddReceiveViewCount(v int64) *UserStatUpdate {
	_u.mutation.AddReceiveViewCount(v)
	return _u
}

// SetFavorCount sets the "favor_count" field.
func (_u *UserStatUpdate) SetFavorCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetFavorCount()
	_u.mutation.SetFavorCount(v)
	return _u
}

// SetNillableFavorCount sets the "favor_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableFavorCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetFavorCount(*v)
	}
	return _u
}

// AddFavorCount adds value to the "favor_count" field.
func (_u *UserStatUpdate) AddFavorCount(v int64) *UserStatUpdate {
	_u.mutation.AddFavorCount(v)
	return _u
}

// SetReceiveFavorCount sets the "receive_favor_count" field.
func (_u *UserStatUpdate) SetReceiveFavorCount(v uint64) *UserStatUpdate {
	_u.mutation.ResetReceiveFavorCount()
	_u.mutation.SetReceiveFavorCount(v)
	return _u
}

// SetNillableReceiveFavorCount sets the "receive_favor_count" field if the given value is not nil.
func (_u *UserStatUpdate) SetNillableReceiveFavorCount(v *uint64) *UserStatUpdate {
	if v != nil {
		_u.SetReceiveFavorCount(*v)
	}
	return _u
}

// AddReceiveFavorCount adds value to the "receive_favor_count" field.
func (_u *UserStatUpdate) AddReceiveFavorCount(v int64) *UserStatUpdate {
	_u.mutation.AddReceiveFavorCount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserStatUpdate) SetUser(v *User) *UserStatUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserStatMutation object of the builder.
func (_u *UserStatUpdate) Mutation() *UserStatMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserStatUpdate) ClearUser() *UserStatUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserStatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserStatUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserStat.user"`)
	}
	return nil
}

func (_u *UserStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstat.Table, userstat.Columns, sqlgraph.NewFieldSpec(userstat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FollowersCount(); ok {
		_spec.SetField(userstat.FieldFollowersCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowersCount(); ok {
		_spec.AddField(userstat.FieldFollowersCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingCount(); ok {
		_spec.SetField(userstat.FieldFollowingCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstat.FieldFollowingCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(userstat.FieldLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(userstat.FieldLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveLikeCount(); ok {
		_spec.SetField(userstat.FieldReceiveLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveLikeCount(); ok {
		_spec.AddField(userstat.FieldReceiveLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(userstat.FieldViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(userstat.FieldViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveViewCount(); ok {
		_spec.SetField(userstat.FieldReceiveViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveViewCount(); ok {
		_spec.AddField(userstat.FieldReceiveViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FavorCount(); ok {
		_spec.SetField(userstat.FieldFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFavorCount(); ok {
		_spec.AddField(userstat.FieldFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveFavorCount(); ok {
		_spec.SetField(userstat.FieldReceiveFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveFavorCount(); ok {
		_spec.AddField(userstat.FieldReceiveFavorCount, field.TypeUint64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstat.UserTable,
			Columns: []string{userstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstat.UserTable,
			Columns: []string{userstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserStatUpdateOne is the builder for updating a single UserStat entity.
type UserStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserStatMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserStatUpdateOne) SetUserID(v uint64) *UserStatUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableUserID(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFollowersCount sets the "followers_count" field.
func (_u *UserStatUpdateOne) SetFollowersCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetFollowersCount()
	_u.mutation.SetFollowersCount(v)
	return _u
}

// SetNillableFollowersCount sets the "followers_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableFollowersCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetFollowersCount(*v)
	}
	return _u
}

// AddFollowersCount adds value to the "followers_count" field.
func (_u *UserStatUpdateOne) AddFollowersCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddFollowersCount(v)
	return _u
}

// SetFollowingCount sets the "following_count" field.
func (_u *UserStatUpdateOne) SetFollowingCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetFollowingCount()
	_u.mutation.SetFollowingCount(v)
	return _u
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableFollowingCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetFollowingCount(*v)
	}
	return _u
}

// AddFollowingCount adds value to the "following_count" field.
func (_u *UserStatUpdateOne) AddFollowingCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddFollowingCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *UserStatUpdateOne) SetLikeCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableLikeCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *UserStatUpdateOne) AddLikeCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetReceiveLikeCount sets the "receive_like_count" field.
func (_u *UserStatUpdateOne) SetReceiveLikeCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetReceiveLikeCount()
	_u.mutation.SetReceiveLikeCount(v)
	return _u
}

// SetNillableReceiveLikeCount sets the "receive_like_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableReceiveLikeCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetReceiveLikeCount(*v)
	}
	return _u
}

// AddReceiveLikeCount adds value to the "receive_like_count" field.
func (_u *UserStatUpdateOne) AddReceiveLikeCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddReceiveLikeCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *UserStatUpdateOne) SetViewCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableViewCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *UserStatUpdateOne) AddViewCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetReceiveViewCount sets the "receive_view_count" field.
func (_u *UserStatUpdateOne) SetReceiveViewCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetReceiveViewCount()
	_u.mutation.SetReceiveViewCount(v)
	return _u
}

// SetNillableReceiveViewCount sets the "receive_view_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableReceiveViewCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetReceiveViewCount(*v)
	}
	return _u
}

// AddReceiveViewCount adds value to the "receive_view_count" field.
func (_u *UserStatUpdateOne) AddReceiveViewCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddReceiveViewCount(v)
	return _u
}

// SetFavorCount sets the "favor_count" field.
func (_u *UserStatUpdateOne) SetFavorCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetFavorCount()
	_u.mutation.SetFavorCount(v)
	return _u
}

// SetNillableFavorCount sets the "favor_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableFavorCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetFavorCount(*v)
	}
	return _u
}

// AddFavorCount adds value to the "favor_count" field.
func (_u *UserStatUpdateOne) AddFavorCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddFavorCount(v)
	return _u
}

// SetReceiveFavorCount sets the "receive_favor_count" field.
func (_u *UserStatUpdateOne) SetReceiveFavorCount(v uint64) *UserStatUpdateOne {
	_u.mutation.ResetReceiveFavorCount()
	_u.mutation.SetReceiveFavorCount(v)
	return _u
}

// SetNillableReceiveFavorCount sets the "receive_favor_count" field if the given value is not nil.
func (_u *UserStatUpdateOne) SetNillableReceiveFavorCount(v *uint64) *UserStatUpdateOne {
	if v != nil {
		_u.SetReceiveFavorCount(*v)
	}
	return _u
}

// AddReceiveFavorCount adds value to the "receive_favor_count" field.
func (_u *UserStatUpdateOne) AddReceiveFavorCount(v int64) *UserStatUpdateOne {
	_u.mutation.AddReceiveFavorCount(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserStatUpdateOne) SetUser(v *User) *UserStatUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserStatMutation object of the builder.
func (_u *UserStatUpdateOne) Mutation() *UserStatMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserStatUpdateOne) ClearUser() *UserStatUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserStatUpdate builder.
func (_u *UserStatUpdateOne) Where(ps ...predicate.UserStat) *UserStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserStatUpdateOne) Select(field string, fields ...string) *UserStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserStat entity.
func (_u *UserStatUpdateOne) Save(ctx context.Context) (*UserStat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserStatUpdateOne) SaveX(ctx context.Context) *UserStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserStatUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserStat.user"`)
	}
	return nil
}

func (_u *UserStatUpdateOne) sqlSave(ctx context.Context) (_node *UserStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userstat.Table, userstat.Columns, sqlgraph.NewFieldSpec(userstat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userstat.FieldID)
		for _, f := range fields {
			if !userstat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userstat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FollowersCount(); ok {
		_spec.SetField(userstat.FieldFollowersCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowersCount(); ok {
		_spec.AddField(userstat.FieldFollowersCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingCount(); ok {
		_spec.SetField(userstat.FieldFollowingCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingCount(); ok {
		_spec.AddField(userstat.FieldFollowingCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(userstat.FieldLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(userstat.FieldLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveLikeCount(); ok {
		_spec.SetField(userstat.FieldReceiveLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveLikeCount(); ok {
		_spec.AddField(userstat.FieldReceiveLikeCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(userstat.FieldViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(userstat.FieldViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveViewCount(); ok {
		_spec.SetField(userstat.FieldReceiveViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveViewCount(); ok {
		_spec.AddField(userstat.FieldReceiveViewCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FavorCount(); ok {
		_spec.SetField(userstat.FieldFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFavorCount(); ok {
		_spec.AddField(userstat.FieldFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReceiveFavorCount(); ok {
		_spec.SetField(userstat.FieldReceiveFavorCount, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReceiveFavorCount(); ok {
		_spec.AddField(userstat.FieldReceiveFavorCount, field.TypeUint64, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstat.UserTable,
			Columns: []string{userstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstat.UserTable,
			Columns: []string{userstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
