// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repov2/ent/user"
	"core-server/internal/infras/repov2/ent/userstat"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserStatCreate is the builder for creating a UserStat entity.
type UserStatCreate struct {
	config
	mutation *UserStatMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserStatCreate) SetCreatedAt(v time.Time) *UserStatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableCreatedAt(v *time.Time) *UserStatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserStatCreate) SetUpdatedAt(v time.Time) *UserStatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableUpdatedAt(v *time.Time) *UserStatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserStatCreate) SetDeletedAt(v time.Time) *UserStatCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableDeletedAt(v *time.Time) *UserStatCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserStatCreate) SetUserID(v uint64) *UserStatCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFollowersCount sets the "followers_count" field.
func (_c *UserStatCreate) SetFollowersCount(v uint64) *UserStatCreate {
	_c.mutation.SetFollowersCount(v)
	return _c
}

// SetNillableFollowersCount sets the "followers_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableFollowersCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetFollowersCount(*v)
	}
	return _c
}

// SetFollowingCount sets the "following_count" field.
func (_c *UserStatCreate) SetFollowingCount(v uint64) *UserStatCreate {
	_c.mutation.SetFollowingCount(v)
	return _c
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableFollowingCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetFollowingCount(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *UserStatCreate) SetLikeCount(v uint64) *UserStatCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableLikeCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetReceiveLikeCount sets the "receive_like_count" field.
func (_c *UserStatCreate) SetReceiveLikeCount(v uint64) *UserStatCreate {
	_c.mutation.SetReceiveLikeCount(v)
	return _c
}

// SetNillableReceiveLikeCount sets the "receive_like_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableReceiveLikeCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetReceiveLikeCount(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *UserStatCreate) SetViewCount(v uint64) *UserStatCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableViewCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetReceiveViewCount sets the "receive_view_count" field.
func (_c *UserStatCreate) SetReceiveViewCount(v uint64) *UserStatCreate {
	_c.mutation.SetReceiveViewCount(v)
	return _c
}

// SetNillableReceiveViewCount sets the "receive_view_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableReceiveViewCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetReceiveViewCount(*v)
	}
	return _c
}

// SetFavorCount sets the "favor_count" field.
func (_c *UserStatCreate) SetFavorCount(v uint64) *UserStatCreate {
	_c.mutation.SetFavorCount(v)
	return _c
}

// SetNillableFavorCount sets the "favor_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableFavorCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetFavorCount(*v)
	}
	return _c
}

// SetReceiveFavorCount sets the "receive_favor_count" field.
func (_c *UserStatCreate) SetReceiveFavorCount(v uint64) *UserStatCreate {
	_c.mutation.SetReceiveFavorCount(v)
	return _c
}

// SetNillableReceiveFavorCount sets the "receive_favor_count" field if the given value is not nil.
func (_c *UserStatCreate) SetNillableReceiveFavorCount(v *uint64) *UserStatCreate {
	if v != nil {
		_c.SetReceiveFavorCount(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserStatCreate) SetUser(v *User) *UserStatCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserStatMutation object of the builder.
func (_c *UserStatCreate) Mutation() *UserStatMutation {
	return _c.mutation
}

// Save creates the UserStat in the database.
func (_c *UserStatCreate) Save(ctx context.Context) (*UserStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserStatCreate) SaveX(ctx context.Context) *UserStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserStatCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userstat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userstat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FollowersCount(); !ok {
		v := userstat.DefaultFollowersCount
		_c.mutation.SetFollowersCount(v)
	}
	if _, ok := _c.mutation.FollowingCount(); !ok {
		v := userstat.DefaultFollowingCount
		_c.mutation.SetFollowingCount(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := userstat.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.ReceiveLikeCount(); !ok {
		v := userstat.DefaultReceiveLikeCount
		_c.mutation.SetReceiveLikeCount(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := userstat.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.ReceiveViewCount(); !ok {
		v := userstat.DefaultReceiveViewCount
		_c.mutation.SetReceiveViewCount(v)
	}
	if _, ok := _c.mutation.FavorCount(); !ok {
		v := userstat.DefaultFavorCount
		_c.mutation.SetFavorCount(v)
	}
	if _, ok := _c.mutation.ReceiveFavorCount(); !ok {
		v := userstat.DefaultReceiveFavorCount
		_c.mutation.SetReceiveFavorCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserStatCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserStat.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserStat.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserStat.user_id"`)}
	}
	if _, ok := _c.mutation.FollowersCount(); !ok {
		return &ValidationError{Name: "followers_count", err: errors.New(`ent: missing required field "UserStat.followers_count"`)}
	}
	if _, ok := _c.mutation.FollowingCount(); !ok {
		return &ValidationError{Name: "following_count", err: errors.New(`ent: missing required field "UserStat.following_count"`)}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "UserStat.like_count"`)}
	}
	if _, ok := _c.mutation.ReceiveLikeCount(); !ok {
		return &ValidationError{Name: "receive_like_count", err: errors.New(`ent: missing required field "UserStat.receive_like_count"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "UserStat.view_count"`)}
	}
	if _, ok := _c.mutation.ReceiveViewCount(); !ok {
		return &ValidationError{Name: "receive_view_count", err: errors.New(`ent: missing required field "UserStat.receive_view_count"`)}
	}
	if _, ok := _c.mutation.FavorCount(); !ok {
		return &ValidationError{Name: "favor_count", err: errors.New(`ent: missing required field "UserStat.favor_count"`)}
	}
	if _, ok := _c.mutation.ReceiveFavorCount(); !ok {
		return &ValidationError{Name: "receive_favor_count", err: errors.New(`ent: missing required field "UserStat.receive_favor_count"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserStat.user"`)}
	}
	return nil
}

func (_c *UserStatCreate) sqlSave(ctx context.Context) (*UserStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserStatCreate) createSpec() (*UserStat, *sqlgraph.CreateSpec) {
	var (
		_node = &UserStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userstat.Table, sqlgraph.NewFieldSpec(userstat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userstat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userstat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(userstat.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.FollowersCount(); ok {
		_spec.SetField(userstat.FieldFollowersCount, field.TypeUint64, value)
		_node.FollowersCount = value
	}
	if value, ok := _c.mutation.FollowingCount(); ok {
		_spec.SetField(userstat.FieldFollowingCount, field.TypeUint64, value)
		_node.FollowingCount = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(userstat.FieldLikeCount, field.TypeUint64, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.ReceiveLikeCount(); ok {
		_spec.SetField(userstat.FieldReceiveLikeCount, field.TypeUint64, value)
		_node.ReceiveLikeCount = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(userstat.FieldViewCount, field.TypeUint64, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.ReceiveViewCount(); ok {
		_spec.SetField(userstat.FieldReceiveViewCount, field.TypeUint64, value)
		_node.ReceiveViewCount = value
	}
	if value, ok := _c.mutation.FavorCount(); ok {
		_spec.SetField(userstat.FieldFavorCount, field.TypeUint64, value)
		_node.FavorCount = value
	}
	if value, ok := _c.mutation.ReceiveFavorCount(); ok {
		_spec.SetField(userstat.FieldReceiveFavorCount, field.TypeUint64, value)
		_node.ReceiveFavorCount = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userstat.UserTable,
			Columns: []string{userstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserStatCreateBulk is the builder for creating many UserStat entities in bulk.
type UserStatCreateBulk struct {
	config
	err      error
	builders []*UserStatCreate
}

// Save creates the UserStat entities in the database.
func (_c *UserStatCreateBulk) Save(ctx context.Context) ([]*UserStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserStatCreateBulk) SaveX(ctx context.Context) []*UserStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
