// Code generated by ent, DO NOT EDIT.

package interactioncount

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the interactioncount type in the database.
	Label = "interaction_count"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldObjectID holds the string denoting the object_id field in the database.
	FieldObjectID = "object_id"
	// FieldObjectType holds the string denoting the object_type field in the database.
	FieldObjectType = "object_type"
	// FieldInteractionType holds the string denoting the interaction_type field in the database.
	FieldInteractionType = "interaction_type"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// Table holds the table name of the interactioncount in the database.
	Table = "interaction_count"
)

// Columns holds all SQL columns for interactioncount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldObjectID,
	FieldObjectType,
	FieldInteractionType,
	FieldCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCount holds the default value on creation for the "count" field.
	DefaultCount int
)

// ObjectType defines the type for the "object_type" enum field.
type ObjectType string

// ObjectType values.
const (
	ObjectTypeArticle ObjectType = "article"
)

func (ot ObjectType) String() string {
	return string(ot)
}

// ObjectTypeValidator is a validator for the "object_type" field enum values. It is called by the builders before save.
func ObjectTypeValidator(ot ObjectType) error {
	switch ot {
	case ObjectTypeArticle:
		return nil
	default:
		return fmt.Errorf("interactioncount: invalid enum value for object_type field: %q", ot)
	}
}

// InteractionType defines the type for the "interaction_type" enum field.
type InteractionType string

// InteractionType values.
const (
	InteractionTypeLike  InteractionType = "like"
	InteractionTypeView  InteractionType = "view"
	InteractionTypeFavor InteractionType = "favor"
)

func (it InteractionType) String() string {
	return string(it)
}

// InteractionTypeValidator is a validator for the "interaction_type" field enum values. It is called by the builders before save.
func InteractionTypeValidator(it InteractionType) error {
	switch it {
	case InteractionTypeLike, InteractionTypeView, InteractionTypeFavor:
		return nil
	default:
		return fmt.Errorf("interactioncount: invalid enum value for interaction_type field: %q", it)
	}
}

// OrderOption defines the ordering options for the InteractionCount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByObjectID orders the results by the object_id field.
func ByObjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectID, opts...).ToFunc()
}

// ByObjectType orders the results by the object_type field.
func ByObjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectType, opts...).ToFunc()
}

// ByInteractionType orders the results by the interaction_type field.
func ByInteractionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInteractionType, opts...).ToFunc()
}

// ByCount orders the results by the count field.
func ByCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCount, opts...).ToFunc()
}
