server:
  addr: "127.0.0.1:8081"

Log:
  Level: "debug"
  # console=仅终端彩色 | file=仅文件JSON
  Mode: "console"
  Filename: "logs/core-server.log"

Mysql:
  Host: "127.0.0.1"
  Port: "3306"
  username: "root"
  password: "123456"
  dbname: "renai"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  Max_Idle_Conn: 10
  Max_Open_Conn: 100

Redis:
  Host: "127.0.0.1"
  Port: "6379"
  username: "root"
  password: ""
  db: 0

Kafka:
  Version: "4.0.0"
  Host: "127.0.0.1:9092"
  MaxRetry: 3
  Timeout: 10
  ConsumerMaxProcessingTime: 10
  # 死信队列，格式: group_id;topic_name;partition_num;replication_factor_num
  DlqTopic: "dlq_group;dlq_topic;1;1"
  LikeTopic: "like_group;like_topic;3;1"

CountAggregator:
  FlushInterval: "5s"
  BufferSize: 100
  DBTimeout: "10s"
