// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: like.proto

// provide user like service
// 1. add like

package likepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1.点赞操作 和 取消点赞
type ThumbUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=objectType,proto3" json:"objectType,omitempty"`
	ObjectID      string                 `protobuf:"bytes,3,opt,name=objectID,proto3" json:"objectID,omitempty"`
	ObjectOwnerID string                 `protobuf:"bytes,4,opt,name=objectOwnerID,proto3" json:"objectOwnerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpRequest) Reset() {
	*x = ThumbUpRequest{}
	mi := &file_like_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpRequest) ProtoMessage() {}

func (x *ThumbUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpRequest.ProtoReflect.Descriptor instead.
func (*ThumbUpRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbUpRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ThumbUpRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ThumbUpRequest) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *ThumbUpRequest) GetObjectOwnerID() string {
	if x != nil {
		return x.ObjectOwnerID
	}
	return ""
}

type ThumbUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbUpResponse) Reset() {
	*x = ThumbUpResponse{}
	mi := &file_like_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbUpResponse) ProtoMessage() {}

func (x *ThumbUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbUpResponse.ProtoReflect.Descriptor instead.
func (*ThumbUpResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbUpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelThumbUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=objectType,proto3" json:"objectType,omitempty"`
	ObjectID      string                 `protobuf:"bytes,3,opt,name=objectID,proto3" json:"objectID,omitempty"`
	ObjectOwnerID string                 `protobuf:"bytes,4,opt,name=objectOwnerID,proto3" json:"objectOwnerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelThumbUpRequest) Reset() {
	*x = CancelThumbUpRequest{}
	mi := &file_like_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelThumbUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelThumbUpRequest) ProtoMessage() {}

func (x *CancelThumbUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelThumbUpRequest.ProtoReflect.Descriptor instead.
func (*CancelThumbUpRequest) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *CancelThumbUpRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CancelThumbUpRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CancelThumbUpRequest) GetObjectID() string {
	if x != nil {
		return x.ObjectID
	}
	return ""
}

func (x *CancelThumbUpRequest) GetObjectOwnerID() string {
	if x != nil {
		return x.ObjectOwnerID
	}
	return ""
}

type CancelThumbUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelThumbUpResponse) Reset() {
	*x = CancelThumbUpResponse{}
	mi := &file_like_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelThumbUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelThumbUpResponse) ProtoMessage() {}

func (x *CancelThumbUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelThumbUpResponse.ProtoReflect.Descriptor instead.
func (*CancelThumbUpResponse) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

func (x *CancelThumbUpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_like_proto protoreflect.FileDescriptor

const file_like_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"like.proto\x12\x04like\"\x8a\x01\n" +
	"\x0eThumbUpRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"objectType\x18\x02 \x01(\tR\n" +
	"objectType\x12\x1a\n" +
	"\bobjectID\x18\x03 \x01(\tR\bobjectID\x12$\n" +
	"\robjectOwnerID\x18\x04 \x01(\tR\robjectOwnerID\"+\n" +
	"\x0fThumbUpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x01\n" +
	"\x14CancelThumbUpRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"objectType\x18\x02 \x01(\tR\n" +
	"objectType\x12\x1a\n" +
	"\bobjectID\x18\x03 \x01(\tR\bobjectID\x12$\n" +
	"\robjectOwnerID\x18\x04 \x01(\tR\robjectOwnerID\"1\n" +
	"\x15CancelThumbUpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x93\x01\n" +
	"\vLikeService\x128\n" +
	"\aThumbUp\x12\x14.like.ThumbUpRequest\x1a\x15.like.ThumbUpResponse\"\x00\x12J\n" +
	"\rCancelThumbUp\x12\x1a.like.CancelThumbUpRequest\x1a\x1b.like.CancelThumbUpResponse\"\x00B0Z.backend/core-server/internal/rpc/likepb;likepbb\x06proto3"

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData []byte
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)))
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_like_proto_goTypes = []any{
	(*ThumbUpRequest)(nil),        // 0: like.ThumbUpRequest
	(*ThumbUpResponse)(nil),       // 1: like.ThumbUpResponse
	(*CancelThumbUpRequest)(nil),  // 2: like.CancelThumbUpRequest
	(*CancelThumbUpResponse)(nil), // 3: like.CancelThumbUpResponse
}
var file_like_proto_depIdxs = []int32{
	0, // 0: like.LikeService.ThumbUp:input_type -> like.ThumbUpRequest
	2, // 1: like.LikeService.CancelThumbUp:input_type -> like.CancelThumbUpRequest
	1, // 2: like.LikeService.ThumbUp:output_type -> like.ThumbUpResponse
	3, // 3: like.LikeService.CancelThumbUp:output_type -> like.CancelThumbUpResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_like_proto_rawDesc), len(file_like_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
