// Code generated by ent, DO NOT EDIT.

package userstat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userstat type in the database.
	Label = "user_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldArticleCount holds the string denoting the article_count field in the database.
	FieldArticleCount = "article_count"
	// FieldFollowersCount holds the string denoting the followers_count field in the database.
	FieldFollowersCount = "followers_count"
	// FieldFollowingCount holds the string denoting the following_count field in the database.
	FieldFollowingCount = "following_count"
	// FieldLikeCount holds the string denoting the like_count field in the database.
	FieldLikeCount = "like_count"
	// FieldReceiveLikeCount holds the string denoting the receive_like_count field in the database.
	FieldReceiveLikeCount = "receive_like_count"
	// FieldFavorCount holds the string denoting the favor_count field in the database.
	FieldFavorCount = "favor_count"
	// FieldReceiveFavorCount holds the string denoting the receive_favor_count field in the database.
	FieldReceiveFavorCount = "receive_favor_count"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userstat in the database.
	Table = "user_stat"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_stat"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userstat fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldArticleCount,
	FieldFollowersCount,
	FieldFollowingCount,
	FieldLikeCount,
	FieldReceiveLikeCount,
	FieldFavorCount,
	FieldReceiveFavorCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultFollowersCount holds the default value on creation for the "followers_count" field.
	DefaultFollowersCount uint64
	// DefaultFollowingCount holds the default value on creation for the "following_count" field.
	DefaultFollowingCount uint64
	// DefaultLikeCount holds the default value on creation for the "like_count" field.
	DefaultLikeCount uint64
	// DefaultReceiveLikeCount holds the default value on creation for the "receive_like_count" field.
	DefaultReceiveLikeCount uint64
	// DefaultFavorCount holds the default value on creation for the "favor_count" field.
	DefaultFavorCount uint64
	// DefaultReceiveFavorCount holds the default value on creation for the "receive_favor_count" field.
	DefaultReceiveFavorCount uint64
)

// OrderOption defines the ordering options for the UserStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByArticleCount orders the results by the article_count field.
func ByArticleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArticleCount, opts...).ToFunc()
}

// ByFollowersCount orders the results by the followers_count field.
func ByFollowersCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFollowersCount, opts...).ToFunc()
}

// ByFollowingCount orders the results by the following_count field.
func ByFollowingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFollowingCount, opts...).ToFunc()
}

// ByLikeCount orders the results by the like_count field.
func ByLikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikeCount, opts...).ToFunc()
}

// ByReceiveLikeCount orders the results by the receive_like_count field.
func ByReceiveLikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiveLikeCount, opts...).ToFunc()
}

// ByFavorCount orders the results by the favor_count field.
func ByFavorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFavorCount, opts...).ToFunc()
}

// ByReceiveFavorCount orders the results by the receive_favor_count field.
func ByReceiveFavorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiveFavorCount, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
