// Code generated by ent, DO NOT EDIT.

package userstat

import (
	"core-server/internal/infras/repov2/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldUserID, v))
}

// FollowersCount applies equality check predicate on the "followers_count" field. It's identical to FollowersCountEQ.
func FollowersCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFollowersCount, v))
}

// FollowingCount applies equality check predicate on the "following_count" field. It's identical to FollowingCountEQ.
func FollowingCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFollowingCount, v))
}

// LikeCount applies equality check predicate on the "like_count" field. It's identical to LikeCountEQ.
func LikeCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldLikeCount, v))
}

// ReceiveLikeCount applies equality check predicate on the "receive_like_count" field. It's identical to ReceiveLikeCountEQ.
func ReceiveLikeCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveLikeCount, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldViewCount, v))
}

// ReceiveViewCount applies equality check predicate on the "receive_view_count" field. It's identical to ReceiveViewCountEQ.
func ReceiveViewCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveViewCount, v))
}

// FavorCount applies equality check predicate on the "favor_count" field. It's identical to FavorCountEQ.
func FavorCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFavorCount, v))
}

// ReceiveFavorCount applies equality check predicate on the "receive_favor_count" field. It's identical to ReceiveFavorCountEQ.
func ReceiveFavorCount(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveFavorCount, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldUserID, vs...))
}

// FollowersCountEQ applies the EQ predicate on the "followers_count" field.
func FollowersCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFollowersCount, v))
}

// FollowersCountNEQ applies the NEQ predicate on the "followers_count" field.
func FollowersCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldFollowersCount, v))
}

// FollowersCountIn applies the In predicate on the "followers_count" field.
func FollowersCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldFollowersCount, vs...))
}

// FollowersCountNotIn applies the NotIn predicate on the "followers_count" field.
func FollowersCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldFollowersCount, vs...))
}

// FollowersCountGT applies the GT predicate on the "followers_count" field.
func FollowersCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldFollowersCount, v))
}

// FollowersCountGTE applies the GTE predicate on the "followers_count" field.
func FollowersCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldFollowersCount, v))
}

// FollowersCountLT applies the LT predicate on the "followers_count" field.
func FollowersCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldFollowersCount, v))
}

// FollowersCountLTE applies the LTE predicate on the "followers_count" field.
func FollowersCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldFollowersCount, v))
}

// FollowingCountEQ applies the EQ predicate on the "following_count" field.
func FollowingCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFollowingCount, v))
}

// FollowingCountNEQ applies the NEQ predicate on the "following_count" field.
func FollowingCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldFollowingCount, v))
}

// FollowingCountIn applies the In predicate on the "following_count" field.
func FollowingCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldFollowingCount, vs...))
}

// FollowingCountNotIn applies the NotIn predicate on the "following_count" field.
func FollowingCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldFollowingCount, vs...))
}

// FollowingCountGT applies the GT predicate on the "following_count" field.
func FollowingCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldFollowingCount, v))
}

// FollowingCountGTE applies the GTE predicate on the "following_count" field.
func FollowingCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldFollowingCount, v))
}

// FollowingCountLT applies the LT predicate on the "following_count" field.
func FollowingCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldFollowingCount, v))
}

// FollowingCountLTE applies the LTE predicate on the "following_count" field.
func FollowingCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldFollowingCount, v))
}

// LikeCountEQ applies the EQ predicate on the "like_count" field.
func LikeCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldLikeCount, v))
}

// LikeCountNEQ applies the NEQ predicate on the "like_count" field.
func LikeCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldLikeCount, v))
}

// LikeCountIn applies the In predicate on the "like_count" field.
func LikeCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldLikeCount, vs...))
}

// LikeCountNotIn applies the NotIn predicate on the "like_count" field.
func LikeCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldLikeCount, vs...))
}

// LikeCountGT applies the GT predicate on the "like_count" field.
func LikeCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldLikeCount, v))
}

// LikeCountGTE applies the GTE predicate on the "like_count" field.
func LikeCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldLikeCount, v))
}

// LikeCountLT applies the LT predicate on the "like_count" field.
func LikeCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldLikeCount, v))
}

// LikeCountLTE applies the LTE predicate on the "like_count" field.
func LikeCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldLikeCount, v))
}

// ReceiveLikeCountEQ applies the EQ predicate on the "receive_like_count" field.
func ReceiveLikeCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveLikeCount, v))
}

// ReceiveLikeCountNEQ applies the NEQ predicate on the "receive_like_count" field.
func ReceiveLikeCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldReceiveLikeCount, v))
}

// ReceiveLikeCountIn applies the In predicate on the "receive_like_count" field.
func ReceiveLikeCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldReceiveLikeCount, vs...))
}

// ReceiveLikeCountNotIn applies the NotIn predicate on the "receive_like_count" field.
func ReceiveLikeCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldReceiveLikeCount, vs...))
}

// ReceiveLikeCountGT applies the GT predicate on the "receive_like_count" field.
func ReceiveLikeCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldReceiveLikeCount, v))
}

// ReceiveLikeCountGTE applies the GTE predicate on the "receive_like_count" field.
func ReceiveLikeCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldReceiveLikeCount, v))
}

// ReceiveLikeCountLT applies the LT predicate on the "receive_like_count" field.
func ReceiveLikeCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldReceiveLikeCount, v))
}

// ReceiveLikeCountLTE applies the LTE predicate on the "receive_like_count" field.
func ReceiveLikeCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldReceiveLikeCount, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldViewCount, v))
}

// ReceiveViewCountEQ applies the EQ predicate on the "receive_view_count" field.
func ReceiveViewCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveViewCount, v))
}

// ReceiveViewCountNEQ applies the NEQ predicate on the "receive_view_count" field.
func ReceiveViewCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldReceiveViewCount, v))
}

// ReceiveViewCountIn applies the In predicate on the "receive_view_count" field.
func ReceiveViewCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldReceiveViewCount, vs...))
}

// ReceiveViewCountNotIn applies the NotIn predicate on the "receive_view_count" field.
func ReceiveViewCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldReceiveViewCount, vs...))
}

// ReceiveViewCountGT applies the GT predicate on the "receive_view_count" field.
func ReceiveViewCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldReceiveViewCount, v))
}

// ReceiveViewCountGTE applies the GTE predicate on the "receive_view_count" field.
func ReceiveViewCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldReceiveViewCount, v))
}

// ReceiveViewCountLT applies the LT predicate on the "receive_view_count" field.
func ReceiveViewCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldReceiveViewCount, v))
}

// ReceiveViewCountLTE applies the LTE predicate on the "receive_view_count" field.
func ReceiveViewCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldReceiveViewCount, v))
}

// FavorCountEQ applies the EQ predicate on the "favor_count" field.
func FavorCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldFavorCount, v))
}

// FavorCountNEQ applies the NEQ predicate on the "favor_count" field.
func FavorCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldFavorCount, v))
}

// FavorCountIn applies the In predicate on the "favor_count" field.
func FavorCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldFavorCount, vs...))
}

// FavorCountNotIn applies the NotIn predicate on the "favor_count" field.
func FavorCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldFavorCount, vs...))
}

// FavorCountGT applies the GT predicate on the "favor_count" field.
func FavorCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldFavorCount, v))
}

// FavorCountGTE applies the GTE predicate on the "favor_count" field.
func FavorCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldFavorCount, v))
}

// FavorCountLT applies the LT predicate on the "favor_count" field.
func FavorCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldFavorCount, v))
}

// FavorCountLTE applies the LTE predicate on the "favor_count" field.
func FavorCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldFavorCount, v))
}

// ReceiveFavorCountEQ applies the EQ predicate on the "receive_favor_count" field.
func ReceiveFavorCountEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldEQ(FieldReceiveFavorCount, v))
}

// ReceiveFavorCountNEQ applies the NEQ predicate on the "receive_favor_count" field.
func ReceiveFavorCountNEQ(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNEQ(FieldReceiveFavorCount, v))
}

// ReceiveFavorCountIn applies the In predicate on the "receive_favor_count" field.
func ReceiveFavorCountIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldIn(FieldReceiveFavorCount, vs...))
}

// ReceiveFavorCountNotIn applies the NotIn predicate on the "receive_favor_count" field.
func ReceiveFavorCountNotIn(vs ...uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldNotIn(FieldReceiveFavorCount, vs...))
}

// ReceiveFavorCountGT applies the GT predicate on the "receive_favor_count" field.
func ReceiveFavorCountGT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGT(FieldReceiveFavorCount, v))
}

// ReceiveFavorCountGTE applies the GTE predicate on the "receive_favor_count" field.
func ReceiveFavorCountGTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldGTE(FieldReceiveFavorCount, v))
}

// ReceiveFavorCountLT applies the LT predicate on the "receive_favor_count" field.
func ReceiveFavorCountLT(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLT(FieldReceiveFavorCount, v))
}

// ReceiveFavorCountLTE applies the LTE predicate on the "receive_favor_count" field.
func ReceiveFavorCountLTE(v uint64) predicate.UserStat {
	return predicate.UserStat(sql.FieldLTE(FieldReceiveFavorCount, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserStat {
	return predicate.UserStat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserStat {
	return predicate.UserStat(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserStat) predicate.UserStat {
	return predicate.UserStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserStat) predicate.UserStat {
	return predicate.UserStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserStat) predicate.UserStat {
	return predicate.UserStat(sql.NotPredicates(p))
}
