// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"core-server/internal/application"
	"core-server/internal/config"
	"core-server/internal/infras/cache"
	"core-server/internal/infras/clog"
	"core-server/internal/infras/mq/kafka"
	"core-server/internal/infras/repo"
	"core-server/internal/jobs/job-dbsync"
	"core-server/internal/rpc"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*rpc.Server, error) {
	dbClient, err := repo.NewDBClient(cfg)
	if err != nil {
		return nil, err
	}
	cacheClient := cache.NewClient(cfg)
	log, err := clog.NewLog(cfg)
	if err != nil {
		return nil, err
	}
	syncProducer, err := kafka.NewSyncProducer(cfg, log)
	if err != nil {
		return nil, err
	}
	topicManager, err := kafka.NewTopicManager(cfg)
	if err != nil {
		return nil, err
	}
	kafkaManager := kafka.NewKafkaManager(cfg, topicManager)
	likeRepo := repo.NewLikeRepo(dbClient)
	countRepo := repo.NewCountRepo(dbClient)
	userRepo := repo.NewUserRepo(dbClient)
	iLikeCache := cache.NewILikeCache(cacheClient)
	messageQueueConsumer := jobdbsync.NewMessageQueueConsumer(cfg, log, syncProducer, kafkaManager, cacheClient, likeRepo, countRepo, userRepo, iLikeCache)
	userService := application.NewUserService(userRepo, log)
	authRPC := rpc.NewAuthRPC(userService)
	articleRepo := repo.NewArticleRepo(dbClient)
	likeService, err := application.NewLikeService(log, likeRepo, iLikeCache, syncProducer, articleRepo, userRepo, cfg)
	if err != nil {
		return nil, err
	}
	likeRPC := rpc.NewLikeRPC(likeService)
	categoryRepo := repo.NewCategoryRepo(dbClient)
	categoryService, err := application.NewCategoryService(log, categoryRepo, cfg)
	if err != nil {
		return nil, err
	}
	categoryRPC := rpc.NewCategoryRPC(categoryService)
	articleService, err := application.NewArticleService(log, articleRepo, userRepo, cfg)
	if err != nil {
		return nil, err
	}
	articleRPC := rpc.NewArticleRPC(articleService)
	commentRepo := repo.NewCommentRepo(dbClient)
	commentService, err := application.NewCommentService(log, commentRepo, userRepo, countRepo, cfg)
	if err != nil {
		return nil, err
	}
	commentRPC := rpc.NewCommentRPC(commentService)
	userRPC := rpc.NewUserRPC(userService)
	server, err := rpc.NewServer(cfg, dbClient, cacheClient, syncProducer, kafkaManager, messageQueueConsumer, authRPC, likeRPC, categoryRPC, articleRPC, commentRPC, userRPC)
	if err != nil {
		return nil, err
	}
	return server, nil
}
