// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"core-server/internal/infras/repo/ent/article"
	"core-server/internal/infras/repo/ent/comment"
	"core-server/internal/infras/repo/ent/predicate"
	"core-server/internal/infras/repo/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentUpdate) SetCreatedAt(v time.Time) *CommentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCreatedAt(v *time.Time) *CommentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CommentUpdate) SetDeletedAt(v time.Time) *CommentUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableDeletedAt(v *time.Time) *CommentUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CommentUpdate) ClearDeletedAt() *CommentUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *CommentUpdate) SetArticleID(v uint64) *CommentUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableArticleID(v *uint64) *CommentUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdate) SetUserID(v uint64) *CommentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableUserID(v *uint64) *CommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *CommentUpdate) SetRootID(v uint64) *CommentUpdate {
	_u.mutation.ResetRootID()
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableRootID(v *uint64) *CommentUpdate {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// AddRootID adds value to the "root_id" field.
func (_u *CommentUpdate) AddRootID(v int64) *CommentUpdate {
	_u.mutation.AddRootID(v)
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *CommentUpdate) SetReplyToID(v uint64) *CommentUpdate {
	_u.mutation.ResetReplyToID()
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableReplyToID(v *uint64) *CommentUpdate {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// AddReplyToID adds value to the "reply_to_id" field.
func (_u *CommentUpdate) AddReplyToID(v int64) *CommentUpdate {
	_u.mutation.AddReplyToID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdate) SetContent(v string) *CommentUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableContent(v *string) *CommentUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *CommentUpdate) SetLikeCount(v uint32) *CommentUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableLikeCount(v *uint32) *CommentUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *CommentUpdate) AddLikeCount(v int32) *CommentUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetChildCount sets the "child_count" field.
func (_u *CommentUpdate) SetChildCount(v uint32) *CommentUpdate {
	_u.mutation.ResetChildCount()
	_u.mutation.SetChildCount(v)
	return _u
}

// SetNillableChildCount sets the "child_count" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableChildCount(v *uint32) *CommentUpdate {
	if v != nil {
		_u.SetChildCount(*v)
	}
	return _u
}

// AddChildCount adds value to the "child_count" field.
func (_u *CommentUpdate) AddChildCount(v int32) *CommentUpdate {
	_u.mutation.AddChildCount(v)
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *CommentUpdate) SetArticle(v *Article) *CommentUpdate {
	return _u.SetArticleID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommentUpdate) SetUser(v *User) *CommentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *CommentUpdate) ClearArticle() *CommentUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommentUpdate) ClearUser() *CommentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdate) check() error {
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.article"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.user"`)
	}
	return nil
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(comment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(comment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(comment.FieldRootID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRootID(); ok {
		_spec.AddField(comment.FieldRootID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(comment.FieldReplyToID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReplyToID(); ok {
		_spec.AddField(comment.FieldReplyToID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(comment.FieldLikeCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(comment.FieldLikeCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ChildCount(); ok {
		_spec.SetField(comment.FieldChildCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedChildCount(); ok {
		_spec.AddField(comment.FieldChildCount, field.TypeUint32, value)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ArticleTable,
			Columns: []string{comment.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ArticleTable,
			Columns: []string{comment.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.UserTable,
			Columns: []string{comment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.UserTable,
			Columns: []string{comment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentUpdateOne) SetCreatedAt(v time.Time) *CommentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCreatedAt(v *time.Time) *CommentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CommentUpdateOne) SetDeletedAt(v time.Time) *CommentUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableDeletedAt(v *time.Time) *CommentUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CommentUpdateOne) ClearDeletedAt() *CommentUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *CommentUpdateOne) SetArticleID(v uint64) *CommentUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableArticleID(v *uint64) *CommentUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdateOne) SetUserID(v uint64) *CommentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableUserID(v *uint64) *CommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRootID sets the "root_id" field.
func (_u *CommentUpdateOne) SetRootID(v uint64) *CommentUpdateOne {
	_u.mutation.ResetRootID()
	_u.mutation.SetRootID(v)
	return _u
}

// SetNillableRootID sets the "root_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableRootID(v *uint64) *CommentUpdateOne {
	if v != nil {
		_u.SetRootID(*v)
	}
	return _u
}

// AddRootID adds value to the "root_id" field.
func (_u *CommentUpdateOne) AddRootID(v int64) *CommentUpdateOne {
	_u.mutation.AddRootID(v)
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *CommentUpdateOne) SetReplyToID(v uint64) *CommentUpdateOne {
	_u.mutation.ResetReplyToID()
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableReplyToID(v *uint64) *CommentUpdateOne {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// AddReplyToID adds value to the "reply_to_id" field.
func (_u *CommentUpdateOne) AddReplyToID(v int64) *CommentUpdateOne {
	_u.mutation.AddReplyToID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *CommentUpdateOne) SetContent(v string) *CommentUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableContent(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *CommentUpdateOne) SetLikeCount(v uint32) *CommentUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableLikeCount(v *uint32) *CommentUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *CommentUpdateOne) AddLikeCount(v int32) *CommentUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetChildCount sets the "child_count" field.
func (_u *CommentUpdateOne) SetChildCount(v uint32) *CommentUpdateOne {
	_u.mutation.ResetChildCount()
	_u.mutation.SetChildCount(v)
	return _u
}

// SetNillableChildCount sets the "child_count" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableChildCount(v *uint32) *CommentUpdateOne {
	if v != nil {
		_u.SetChildCount(*v)
	}
	return _u
}

// AddChildCount adds value to the "child_count" field.
func (_u *CommentUpdateOne) AddChildCount(v int32) *CommentUpdateOne {
	_u.mutation.AddChildCount(v)
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *CommentUpdateOne) SetArticle(v *Article) *CommentUpdateOne {
	return _u.SetArticleID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CommentUpdateOne) SetUser(v *User) *CommentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *CommentUpdateOne) ClearArticle() *CommentUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CommentUpdateOne) ClearUser() *CommentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommentUpdateOne) check() error {
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.article"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Comment.user"`)
	}
	return nil
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(comment.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(comment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RootID(); ok {
		_spec.SetField(comment.FieldRootID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedRootID(); ok {
		_spec.AddField(comment.FieldRootID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(comment.FieldReplyToID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedReplyToID(); ok {
		_spec.AddField(comment.FieldReplyToID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(comment.FieldLikeCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(comment.FieldLikeCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.ChildCount(); ok {
		_spec.SetField(comment.FieldChildCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedChildCount(); ok {
		_spec.AddField(comment.FieldChildCount, field.TypeUint32, value)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ArticleTable,
			Columns: []string{comment.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ArticleTable,
			Columns: []string{comment.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.UserTable,
			Columns: []string{comment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.UserTable,
			Columns: []string{comment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
