// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserStat is the predicate function for userstat builders.
type UserStat func(*sql.Selector)
